### ISSUE TITLE
Updated json in my fork but doesn't show up

### ISSUE THREAD

**Issue by jdschmi1** [zetoken/bf-helper#1]
Hey, I forked your repo and updated the json files w/ all the current global craftables (including raid crafts). For some reason not all of the materials are showing up (http://jdschmi1.github.io/bf-helper/)

If you try and find red crystal it doesn't appear anywhere neither does the item it is used to craft in to (Reveleation Book). If you look at the JSON it has: 
  "Revelation Book": {
    "Origin Slate": 1,
    "Royal Bud": 2,
    "Red Crystal": 15,
    "Flower Core": 2,
    "Red Feather": 2
  },

Am I missing updating other file locations?

**Comment by jdschmi1** [comment]
My Local Storage was using old cached values

**Comment by zetoken** [comment]
I'm going to add a "refresh" button to allow new remote json files to be locally updated.
I will also merge your json files.
